#!/bin/bash

# YUI Test directories
ln -fs ../../../build yui2.8/tests/animation/tests/yui
ln -fs ../../../build yui2.8/tests/autocomplete/tests/yui
ln -fs ../../../build yui2.8/tests/button/tests/yui
ln -fs ../../../build yui2.8/tests/calendar/tests/yui
ln -fs ../../../build yui2.8/tests/carousel/tests/yui
ln -fs ../../../build yui2.8/tests/colorpicker/tests/yui
ln -fs ../../../build yui2.8/tests/common/tests/yui
ln -fs ../../../build yui2.8/tests/connection/tests/yui
ln -fs ../../../build yui2.8/tests/container/tests/yui
ln -fs ../../../build yui2.8/tests/cookie/tests/yui
ln -fs ../../../build yui2.8/tests/datasource/tests/yui
ln -fs ../../../build yui2.8/tests/datatable/tests/yui
ln -fs ../../../build yui2.8/tests/datemath/tests/yui
ln -fs ../../../build yui2.8/tests/dom/tests/yui
ln -fs ../../../build yui2.8/tests/dragdrop/tests/yui
ln -fs ../../../build yui2.8/tests/editor/tests/yui
ln -fs ../../../build yui2.8/tests/element/tests/yui
ln -fs ../../../build yui2.8/tests/event/tests/yui
ln -fs ../../../build yui2.8/tests/event-delegate/tests/yui
ln -fs ../../../build yui2.8/tests/event-mouseenter/tests/yui
ln -fs ../../../build yui2.8/tests/imageloader/tests/yui
ln -fs ../../../build yui2.8/tests/json/tests/yui
ln -fs ../../../build yui2.8/tests/logger/tests/yui
ln -fs ../../../build yui2.8/tests/menu/tests/yui
ln -fs ../../../build yui2.8/tests/paginator/tests/yui
ln -fs ../../../build yui2.8/tests/profiler/tests/yui
ln -fs ../../../build yui2.8/tests/progressbar/tests/yui
ln -fs ../../../build yui2.8/tests/selector/tests/yui
ln -fs ../../../build yui2.8/tests/slider/tests/yui
ln -fs ../../../build yui2.8/tests/storage/tests/yui
ln -fs ../../../build yui2.8/tests/stylesheet/tests/yui
ln -fs ../../../build yui2.8/tests/swf/tests/yui
ln -fs ../../../build yui2.8/tests/tabview/tests/yui
ln -fs ../../../build yui2.8/tests/yahoo/tests/yui
ln -fs ../../../build yui2.8/tests/yuiloader/tests/yui
ln -fs ../../../build yui2.8/tests/yuitest/tests/yui

# Example directories
ln -fs ../../build yui2.8/examples/animation/yui
ln -fs ../../build yui2.8/examples/autocomplete/yui
ln -fs ../../build yui2.8/examples/base/yui
ln -fs ../../build yui2.8/examples/button/yui
ln -fs ../../build yui2.8/examples/calendar/yui
ln -fs ../../build yui2.8/examples/carousel/yui
ln -fs ../../build yui2.8/examples/charts/yui
ln -fs ../../build yui2.8/examples/colorpicker/yui
ln -fs ../../build yui2.8/examples/connection/yui
ln -fs ../../build yui2.8/examples/container/yui
ln -fs ../../build yui2.8/examples/cookie/yui
ln -fs ../../build yui2.8/examples/datasource/yui
ln -fs ../../build yui2.8/examples/datatable/yui
ln -fs ../../build yui2.8/examples/dom/yui
ln -fs ../../build yui2.8/examples/dragdrop/yui
ln -fs ../../build yui2.8/examples/editor/yui
ln -fs ../../build yui2.8/examples/event/yui
ln -fs ../../build yui2.8/examples/fonts/yui
ln -fs ../../build yui2.8/examples/get/yui
ln -fs ../../build yui2.8/examples/grids/yui
ln -fs ../../build yui2.8/examples/history/yui
ln -fs ../../build yui2.8/examples/imagecropper/yui
ln -fs ../../build yui2.8/examples/imageloader/yui
ln -fs ../../build yui2.8/examples/json/yui
ln -fs ../../build yui2.8/examples/layout/yui
ln -fs ../../build yui2.8/examples/logger/yui
ln -fs ../../build yui2.8/examples/menu/yui
ln -fs ../../build yui2.8/examples/paginator/yui
ln -fs ../../build yui2.8/examples/profiler/yui
ln -fs ../../build yui2.8/examples/profilerviewer/yui
ln -fs ../../build yui2.8/examples/progressbar/yui
ln -fs ../../build yui2.8/examples/reset/yui
ln -fs ../../build yui2.8/examples/resize/yui
ln -fs ../../build yui2.8/examples/selector/yui
ln -fs ../../build yui2.8/examples/slider/yui
ln -fs ../../build yui2.8/examples/storage/yui
ln -fs ../../build yui2.8/examples/stylesheet/yui
ln -fs ../../build yui2.8/examples/swf/yui
ln -fs ../../build yui2.8/examples/swfstore/yui
ln -fs ../../build yui2.8/examples/tabview/yui
ln -fs ../../build yui2.8/examples/treeview/yui
ln -fs ../../build yui2.8/examples/uploader/yui
ln -fs ../../build yui2.8/examples/yahoo/yui
ln -fs ../../build yui2.8/examples/yuiloader/yui
ln -fs ../../build yui2.8/examples/yuitest/yui
